import type { PermissionCode, RoleDefinition } from '@/types/permission';

export const allPermissions: PermissionCode[] = [
  'dashboard:view',
  'asset:view',
  'asset:create',
  'asset:edit',
  'asset:intake',
  'asset:transfer',
  'asset:disposal',
  'asset:inventory',
  'asset:approve',
  'equipment:view',
  'equipment:edit',
  'equipment:attachment',
  'spare:view',
  'spare:edit',
  'spare:stock',
  'spare:inbound',
  'spare:outbound',
  'spare:inventory',
  'spare:alert',
  'spare:approve',
  'mom:view',
  'analytics:asset',
  'analytics:factory',
  'analytics:maintenance',
  'analytics:finance',
  'analytics:spare',
  'integration:mom',
  'integration:finance',
  'integration:project',
  'system:org',
  'system:user',
  'system:role',
  'system:log',
];

const viewPermissions: PermissionCode[] = [
  'dashboard:view',
  'asset:view',
  'equipment:view',
  'spare:view',
  'spare:stock',
  'spare:alert',
  'mom:view',
  'analytics:asset',
  'analytics:factory',
  'analytics:maintenance',
  'analytics:finance',
  'analytics:spare',
];

export const roleDefinitions: RoleDefinition[] = [
  {
    key: 'system_admin',
    name: '系统管理员',
    description: '负责组织、用户、角色、菜单、按钮与数据范围配置。',
    permissions: allPermissions,
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
  {
    key: 'asset_admin',
    name: '资产管理员',
    description: '负责固定资产台账、入账、调拨、处置与盘点。',
    permissions: [
      ...viewPermissions,
      'asset:create',
      'asset:edit',
      'asset:intake',
      'asset:transfer',
      'asset:disposal',
      'asset:inventory',
      'asset:approve',
      'equipment:attachment',
      'integration:finance',
      'integration:project',
      'system:log',
    ],
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
  {
    key: 'equipment_admin',
    name: '设备档案管理员',
    description: '负责一机一档、技术参数、验收资料、合同证件与影像资料。',
    permissions: [
      'dashboard:view',
      'asset:view',
      'equipment:view',
      'equipment:edit',
      'equipment:attachment',
      'spare:view',
      'mom:view',
      'analytics:asset',
      'analytics:maintenance',
      'system:log',
    ],
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
  {
    key: 'spare_admin',
    name: '备件管理员',
    description: '负责备件台账、库存、入库、出库、盘点和预警。',
    permissions: [
      'dashboard:view',
      'asset:view',
      'equipment:view',
      'spare:view',
      'spare:edit',
      'spare:stock',
      'spare:inbound',
      'spare:outbound',
      'spare:inventory',
      'spare:alert',
      'spare:approve',
      'mom:view',
      'analytics:spare',
      'system:log',
    ],
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
  {
    key: 'factory_manager',
    name: '厂区/部门负责人',
    description: '负责本厂区资产、备件业务申请与审批。',
    permissions: [
      ...viewPermissions,
      'asset:transfer',
      'asset:disposal',
      'asset:inventory',
      'asset:approve',
      'spare:outbound',
      'spare:inventory',
      'spare:approve',
      'system:log',
    ],
    dataScope: 'factory',
    factoryIds: ['fac-nb'],
  },
  {
    key: 'finance',
    name: '财务人员',
    description: '负责固定资产编号、价值变动、折旧、净值和处置核销确认。',
    permissions: [
      'dashboard:view',
      'asset:view',
      'asset:intake',
      'asset:disposal',
      'mom:view',
      'analytics:asset',
      'analytics:finance',
      'integration:finance',
      'system:log',
    ],
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
  {
    key: 'maintenance',
    name: '维修/保养人员',
    description: '查看设备档案和 MOM 数据，发起备件领用与退库。',
    permissions: [
      'dashboard:view',
      'asset:view',
      'equipment:view',
      'spare:view',
      'spare:stock',
      'spare:outbound',
      'mom:view',
      'analytics:maintenance',
    ],
    dataScope: 'factory',
    factoryIds: ['fac-cq'],
  },
  {
    key: 'executive',
    name: '管理层',
    description: '查看集团级资产、厂区对比、维修、费用和备件分析。',
    permissions: viewPermissions,
    dataScope: 'group',
    factoryIds: ['fac-nb', 'fac-sz', 'fac-cq', 'fac-ah'],
  },
];

export const permissionNameMap = new Map<PermissionCode, string>([
  ['dashboard:view', '首页看板'],
  ['asset:view', '资产查看'],
  ['asset:create', '资产新增'],
  ['asset:edit', '资产编辑'],
  ['asset:intake', '资产入账'],
  ['asset:transfer', '资产调拨'],
  ['asset:disposal', '资产处置'],
  ['asset:inventory', '资产盘点'],
  ['asset:approve', '资产审批'],
  ['equipment:view', '设备档案查看'],
  ['equipment:edit', '设备档案维护'],
  ['equipment:attachment', '档案附件维护'],
  ['spare:view', '备件查看'],
  ['spare:edit', '备件维护'],
  ['spare:stock', '备件库存'],
  ['spare:inbound', '备件入库'],
  ['spare:outbound', '备件出库'],
  ['spare:inventory', '备件盘点'],
  ['spare:alert', '备件预警'],
  ['spare:approve', '备件审批'],
  ['mom:view', 'MOM 数据展示'],
  ['analytics:asset', '资产分析'],
  ['analytics:factory', '厂区对比'],
  ['analytics:maintenance', '维修分析'],
  ['analytics:finance', '费用分析'],
  ['analytics:spare', '备件分析'],
  ['integration:mom', 'MOM 对接'],
  ['integration:finance', '财务对接'],
  ['integration:project', '项目管理对接'],
  ['system:org', '组织架构'],
  ['system:user', '用户管理'],
  ['system:role', '角色权限'],
  ['system:log', '操作日志'],
]);
