import type { ManagementPageConfig } from './types';

const viewAction = { key: 'view', label: '详情' };

export const extensionPageConfigs: Record<string, ManagementPageConfig> = {
  'assets.import': {
    key: 'assets.import',
    title: '批量导入',
    apiPath: '/assets/import',
    permission: 'asset:intake',
    editPermission: 'asset:intake',
    columns: [
      { title: '导入单号', dataIndex: 'billCode', width: 150 },
      { title: '资产名称', dataIndex: 'assetName', width: 220 },
      { title: '来源系统', dataIndex: 'sourceSystem', kind: 'status', width: 110 },
      { title: '验收项目', dataIndex: 'projectName', width: 220 },
      { title: '财务编号', dataIndex: 'financeAssetCode', width: 160 },
      { title: '导入状态', dataIndex: 'status', kind: 'status', width: 110 },
      { title: '创建时间', dataIndex: 'createdAt', width: 160 },
    ],
    actions: [viewAction, { key: 'book', label: '入账', permission: 'asset:intake', primary: true }],
    statusSearch: true,
  },
  'assets.map': {
    key: 'assets.map',
    title: '资产地图',
    apiPath: '/assets/map',
    permission: 'asset:view',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '资产名称', dataIndex: 'name', width: 190 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '车间', dataIndex: 'workshopName', width: 160 },
      { title: '产线', dataIndex: 'lineName', width: 170 },
      { title: '位置', dataIndex: 'location', width: 120 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction],
    statusSearch: true,
  },
  'assets.usage': {
    key: 'assets.usage',
    title: '日常使用',
    apiPath: '/assets/usage',
    permission: 'asset:view',
    editPermission: 'asset:edit',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '资产名称', dataIndex: 'name', width: 190 },
      { title: '使用部门', dataIndex: 'ownerDepartment', width: 150 },
      { title: '责任人', dataIndex: 'responsiblePerson', width: 100 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'asset:edit', primary: true }],
    statusSearch: true,
  },
  'assets.history': {
    key: 'assets.history',
    title: '历史追溯',
    apiPath: '/assets/history',
    permission: 'asset:view',
    columns: [
      { title: '操作人', dataIndex: 'operator', width: 100 },
      { title: '模块', dataIndex: 'module', width: 130 },
      { title: '动作', dataIndex: 'action', width: 150 },
      { title: '对象', dataIndex: 'target', width: 170 },
      { title: '结果', dataIndex: 'result', kind: 'status', width: 90 },
      { title: '时间', dataIndex: 'createdAt', width: 160 },
    ],
    actions: [viewAction],
    statusSearch: true,
  },
  'equipment.params': {
    key: 'equipment.params',
    title: '技术参数',
    apiPath: '/equipment/params',
    permission: 'equipment:view',
    editPermission: 'equipment:edit',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '型号', dataIndex: 'model', width: 120 },
      { title: '厂家', dataIndex: 'manufacturer', width: 130 },
      { title: '技术参数', dataIndex: 'technicalParamsText', width: 360 },
      { title: '最近变更', dataIndex: 'latestChangedAt', width: 160 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'equipment:edit', primary: true }],
  },
  'equipment.changes': {
    key: 'equipment.changes',
    title: '变更记录',
    apiPath: '/equipment/changes',
    permission: 'equipment:view',
    editPermission: 'equipment:edit',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '变更内容', dataIndex: 'content', width: 320 },
      { title: '变更人', dataIndex: 'changedBy', width: 100 },
      { title: '变更日期', dataIndex: 'changedAt', width: 130 },
    ],
    actions: [viewAction, { key: 'create', label: '新建', permission: 'equipment:edit', primary: true }],
  },
  'equipment.acceptance': {
    key: 'equipment.acceptance',
    title: '验收资料',
    apiPath: '/equipment/acceptance',
    permission: 'equipment:attachment',
    editPermission: 'equipment:attachment',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '文件名', dataIndex: 'fileName', width: 260 },
      { title: '上传人', dataIndex: 'uploader', width: 100 },
      { title: '上传时间', dataIndex: 'uploadedAt', width: 130 },
      { title: '大小', dataIndex: 'size', width: 90 },
    ],
    actions: [viewAction, { key: 'upload', label: '上传', permission: 'equipment:attachment', primary: true }],
  },
  'equipment.contracts': {
    key: 'equipment.contracts',
    title: '合同证件',
    apiPath: '/equipment/contracts',
    permission: 'equipment:attachment',
    editPermission: 'equipment:attachment',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '文件名', dataIndex: 'fileName', width: 260 },
      { title: '类型', dataIndex: 'type', width: 110 },
      { title: '上传人', dataIndex: 'uploader', width: 100 },
      { title: '上传时间', dataIndex: 'uploadedAt', width: 130 },
    ],
    actions: [viewAction, { key: 'upload', label: '上传', permission: 'equipment:attachment', primary: true }],
  },
  'equipment.images': {
    key: 'equipment.images',
    title: '图片影像',
    apiPath: '/equipment/images',
    permission: 'equipment:attachment',
    editPermission: 'equipment:attachment',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '图片名称', dataIndex: 'fileName', width: 260 },
      { title: '上传人', dataIndex: 'uploader', width: 100 },
      { title: '上传时间', dataIndex: 'uploadedAt', width: 130 },
      { title: '大小', dataIndex: 'size', width: 90 },
    ],
    actions: [viewAction, { key: 'upload', label: '上传', permission: 'equipment:attachment', primary: true }],
  },
  'spares.applicableAssets': {
    key: 'spares.applicableAssets',
    title: '适用设备',
    apiPath: '/spares/applicable-assets',
    permission: 'spare:view',
    editPermission: 'spare:edit',
    columns: [
      { title: '备件编码', dataIndex: 'spareCode', width: 160 },
      { title: '备件名称', dataIndex: 'name', width: 170 },
      { title: '规格', dataIndex: 'spec', width: 130 },
      { title: '适用设备', dataIndex: 'applicableAssetCodes', kind: 'list', width: 300 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
    ],
    actions: [viewAction, { key: 'edit', label: '绑定', permission: 'spare:edit', primary: true }],
  },
  'spares.returns': {
    key: 'spares.returns',
    title: '未用退库',
    apiPath: '/spares/returns',
    permission: 'spare:outbound',
    editPermission: 'spare:outbound',
    columns: [
      { title: '退库单号', dataIndex: 'billCode', width: 140 },
      { title: '备件编码', dataIndex: 'spareCode', width: 150 },
      { title: '备件名称', dataIndex: 'spareName', width: 170 },
      { title: '数量', dataIndex: 'quantity', kind: 'number', width: 80 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '来源单据', dataIndex: 'sourceBill', width: 140 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction, { key: 'create', label: '退库', permission: 'spare:outbound', primary: true }],
    statusSearch: true,
  },
  'spares.consumption': {
    key: 'spares.consumption',
    title: '备件消耗',
    apiPath: '/spares/consumption',
    permission: 'spare:stock',
    columns: [
      { title: '出库单号', dataIndex: 'billCode', width: 140 },
      { title: '出库类型', dataIndex: 'outboundType', kind: 'status', width: 110 },
      { title: '备件编码', dataIndex: 'spareCode', width: 150 },
      { title: '备件名称', dataIndex: 'spareName', width: 170 },
      { title: '数量', dataIndex: 'quantity', kind: 'number', width: 80 },
      { title: '关联设备', dataIndex: 'relatedAssetCode', width: 150 },
      { title: '用途', dataIndex: 'purpose', width: 220 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
    ],
    actions: [viewAction],
  },
  'maintenance.runtime': {
    key: 'maintenance.runtime',
    title: '运行状态',
    apiPath: '/maintenance/runtime',
    permission: 'mom:view',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 190 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '产线', dataIndex: 'lineName', width: 160 },
      { title: '状态', dataIndex: 'state', kind: 'status', width: 90 },
      { title: 'OEE', dataIndex: 'oee', kind: 'percent', width: 90 },
      { title: '更新时间', dataIndex: 'updatedAt', width: 160 },
    ],
    actions: [viewAction],
    statusSearch: true,
  },
  'maintenance.repairs': {
    key: 'maintenance.repairs',
    title: '维修记录',
    apiPath: '/maintenance/repairs',
    permission: 'mom:view',
    columns: [
      { title: '工单', dataIndex: 'workOrder', width: 130 },
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 190 },
      { title: '故障原因', dataIndex: 'faultReason', width: 220 },
      { title: '维修方案', dataIndex: 'solution', width: 260 },
      { title: '费用', dataIndex: 'cost', kind: 'money', width: 120 },
      { title: '维修人', dataIndex: 'repairedBy', width: 90 },
    ],
    actions: [viewAction],
  },
  'maintenance.records': {
    key: 'maintenance.records',
    title: '保养记录',
    apiPath: '/maintenance/records',
    permission: 'mom:view',
    columns: [
      { title: '工单', dataIndex: 'workOrder', width: 130 },
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 190 },
      { title: '保养内容', dataIndex: 'content', width: 260 },
      { title: '更换备件', dataIndex: 'replacedSpares', width: 200 },
      { title: '保养人', dataIndex: 'maintainedBy', width: 90 },
      { title: '保养时间', dataIndex: 'maintainedAt', width: 150 },
    ],
    actions: [viewAction],
  },
  'maintenance.alerts': {
    key: 'maintenance.alerts',
    title: '故障告警',
    apiPath: '/maintenance/alerts',
    permission: 'mom:view',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 190 },
      { title: '等级', dataIndex: 'level', kind: 'status', width: 90 },
      { title: '告警内容', dataIndex: 'message', width: 320 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '时间', dataIndex: 'createdAt', width: 150 },
    ],
    actions: [viewAction],
    statusSearch: true,
  },
  'analytics.warnings': {
    key: 'analytics.warnings',
    title: '预警看板',
    apiPath: '/analytics/warnings',
    permission: 'analytics:spare',
    columns: [
      { title: '预警类型', dataIndex: 'warningType', width: 120 },
      { title: '对象', dataIndex: 'targetName', width: 200 },
      { title: '等级/状态', dataIndex: 'alertType', kind: 'status', width: 120 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '建议', dataIndex: 'suggestion', width: 280 },
      { title: '时间', dataIndex: 'createdAt', width: 150 },
    ],
    actions: [viewAction],
    statusSearch: true,
  },
  'integrations.syncRecords': {
    key: 'integrations.syncRecords',
    title: '同步记录',
    apiPath: '/integrations/sync-records',
    permission: 'integration:mom',
    columns: [
      { title: '业务编码', dataIndex: 'bizCode', width: 180 },
      { title: '业务类型', dataIndex: 'bizType', width: 140 },
      { title: '方向', dataIndex: 'direction', kind: 'status', width: 90 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 90 },
      { title: '摘要', dataIndex: 'summary', width: 320 },
      { title: '时间', dataIndex: 'createdAt', width: 150 },
    ],
    actions: [viewAction, { key: 'sync', label: '重试', permission: 'integration:mom', primary: true }],
    statusSearch: true,
  },
  'integrations.fields': {
    key: 'integrations.fields',
    title: '字段映射',
    apiPath: '/integrations/fields',
    permission: 'integration:mom',
    editPermission: 'integration:mom',
    columns: [
      { title: '来源字段', dataIndex: 'sourceField', width: 160 },
      { title: '目标字段', dataIndex: 'targetField', width: 160 },
      { title: '说明', dataIndex: 'description', width: 260 },
      { title: '必填', dataIndex: 'required', width: 90 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'integration:mom', primary: true }],
  },
};
