import type { ManagementPageConfig } from './types';
import { extensionPageConfigs } from './extensionPageConfigs';

const viewAction = { key: 'view', label: '详情' };

const basePageConfigs: Record<string, ManagementPageConfig> = {
  'assets.list': {
    key: 'assets.list',
    title: '固定资产台账',
    subTitle: '统一资产编码、分类、财务编号、厂区位置和资产状态。',
    apiPath: '/assets/list',
    permission: 'asset:view',
    editPermission: 'asset:edit',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '资产名称', dataIndex: 'name', width: 190 },
      { title: '分类', dataIndex: 'category', width: 110 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '车间', dataIndex: 'workshopName', width: 140 },
      { title: '产线', dataIndex: 'lineName', width: 150 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
      { title: '原值', dataIndex: 'originalValue', kind: 'money', width: 130, search: false },
      { title: '净值', dataIndex: 'netValue', kind: 'money', width: 130, search: false },
      { title: '责任人', dataIndex: 'responsiblePerson', width: 90 },
      { title: '财务编号', dataIndex: 'financeAssetCode', width: 150 },
    ],
    actions: [
      viewAction,
      { key: 'edit', label: '编辑', permission: 'asset:edit' },
      { key: 'transfer', label: '调拨', permission: 'asset:transfer', primary: true },
      { key: 'disposal', label: '处置', permission: 'asset:disposal', danger: true },
    ],
    coverage: ['FR-001 至 FR-009', 'FR-011', 'FR-014', 'FR-017'],
    statusSearch: true,
  },
  'assets.intake': {
    key: 'assets.intake',
    title: '资产入账',
    subTitle: '接收财务、项目管理、手工录入和 Excel 导入的转固数据。',
    apiPath: '/assets/intake',
    permission: 'asset:intake',
    editPermission: 'asset:intake',
    columns: [
      { title: '转固单号', dataIndex: 'billCode', width: 150 },
      { title: '资产名称', dataIndex: 'assetName', width: 220 },
      { title: '来源系统', dataIndex: 'sourceSystem', kind: 'status', width: 110 },
      { title: '验收项目', dataIndex: 'projectName', width: 220 },
      { title: '财务编号', dataIndex: 'financeAssetCode', width: 160 },
      { title: '入账状态', dataIndex: 'status', kind: 'status', width: 110 },
      { title: '创建时间', dataIndex: 'createdAt', width: 160 },
    ],
    actions: [
      viewAction,
      { key: 'book', label: '入账', permission: 'asset:intake', primary: true },
      { key: 'archive', label: '补档', permission: 'equipment:attachment' },
    ],
    coverage: ['FR-010', 'FR-053 至 FR-060'],
    statusSearch: true,
  },
  'assets.transfer': {
    key: 'assets.transfer',
    title: '资产调拨',
    subTitle: '跨部门、跨厂区调拨申请、双方审批、执行和财务同步。',
    apiPath: '/assets/transfer',
    permission: 'asset:transfer',
    editPermission: 'asset:transfer',
    approvePermission: 'asset:approve',
    columns: [
      { title: '调拨单号', dataIndex: 'bizCode', width: 140 },
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '资产名称', dataIndex: 'assetName', width: 180 },
      { title: '调出厂区', dataIndex: 'fromFactory', width: 150 },
      { title: '调入厂区', dataIndex: 'toFactory', width: 160 },
      { title: '申请人', dataIndex: 'applicant', width: 90 },
      { title: '审批人', dataIndex: 'approver', width: 130 },
      { title: '审批状态', dataIndex: 'status', kind: 'status', width: 110 },
      { title: '财务同步', dataIndex: 'financeSyncStatus', kind: 'status', width: 110 },
    ],
    actions: [viewAction, { key: 'create', label: '新建', permission: 'asset:transfer', primary: true }, { key: 'approve', label: '审批', permission: 'asset:approve' }],
    coverage: ['FR-012', 'FR-013', 'FR-017', 'FR-028', 'FR-029'],
    statusSearch: true,
  },
  'assets.disposal': {
    key: 'assets.disposal',
    title: '资产处置',
    subTitle: '出售、报废申请，审批流和财务处置核销记录。',
    apiPath: '/assets/disposal',
    permission: 'asset:disposal',
    editPermission: 'asset:disposal',
    approvePermission: 'asset:approve',
    columns: [
      { title: '处置单号', dataIndex: 'bizCode', width: 140 },
      { title: '资产编码', dataIndex: 'assetCode', width: 150 },
      { title: '资产名称', dataIndex: 'assetName', width: 180 },
      { title: '处置类型', dataIndex: 'disposalType', kind: 'status', width: 100 },
      { title: '原因', dataIndex: 'reason', width: 240 },
      { title: '评估金额', dataIndex: 'evaluationAmount', kind: 'money', width: 130 },
      { title: '审批状态', dataIndex: 'status', kind: 'status', width: 100 },
      { title: '核销状态', dataIndex: 'financeWriteOffStatus', kind: 'status', width: 110 },
    ],
    actions: [viewAction, { key: 'create', label: '新建', permission: 'asset:disposal', primary: true }, { key: 'approve', label: '审批', permission: 'asset:approve' }],
    coverage: ['FR-015', 'FR-016', 'FR-017'],
    statusSearch: true,
  },
  'assets.inventory': {
    key: 'assets.inventory',
    title: '资产盘点',
    subTitle: '盘点计划、扫码盘点结果和盘点差异处理。',
    apiPath: '/assets/inventory',
    permission: 'asset:inventory',
    editPermission: 'asset:inventory',
    approvePermission: 'asset:approve',
    columns: [
      { title: '计划编号', dataIndex: 'planCode', width: 170 },
      { title: '计划名称', dataIndex: 'planName', width: 230 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '范围', dataIndex: 'scope', width: 170 },
      { title: '应盘', dataIndex: 'expectedQty', kind: 'number', width: 90 },
      { title: '已盘', dataIndex: 'checkedQty', kind: 'number', width: 90 },
      { title: '差异', dataIndex: 'diffQty', kind: 'number', width: 90 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
      { title: '截止日期', dataIndex: 'deadline', width: 120 },
    ],
    actions: [viewAction, { key: 'scan', label: '扫码', permission: 'asset:inventory', primary: true }, { key: 'diff', label: '差异', permission: 'asset:approve' }],
    coverage: ['FR-009'],
    statusSearch: true,
  },
  'equipment.files': {
    key: 'equipment.files',
    title: '一机一档',
    subTitle: '设备基础信息、技术参数、验收资料、证件影像和变更记录。',
    apiPath: '/equipment/files',
    permission: 'equipment:view',
    editPermission: 'equipment:edit',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '型号', dataIndex: 'model', width: 120 },
      { title: '厂家', dataIndex: 'manufacturer', width: 130 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '完整度', dataIndex: 'completionRate', kind: 'percent', width: 100 },
      { title: '最近变更', dataIndex: 'latestChangedAt', width: 160 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'equipment:edit' }, { key: 'upload', label: '上传', permission: 'equipment:attachment', primary: true }],
    coverage: ['FR-018 至 FR-025'],
  },
  'equipment.attachments': {
    key: 'equipment.attachments',
    title: '档案附件',
    subTitle: '验收报告、合同证件、图片资料和技术资料集中维护。',
    apiPath: '/equipment/attachments',
    permission: 'equipment:attachment',
    editPermission: 'equipment:attachment',
    columns: [
      { title: '资产编码', dataIndex: 'assetCode', width: 160 },
      { title: '设备名称', dataIndex: 'equipmentName', width: 210 },
      { title: '文件名', dataIndex: 'fileName', width: 240 },
      { title: '类型', dataIndex: 'type', width: 110 },
      { title: '上传人', dataIndex: 'uploader', width: 90 },
      { title: '上传时间', dataIndex: 'uploadedAt', width: 120 },
      { title: '大小', dataIndex: 'size', width: 90 },
    ],
    actions: [viewAction, { key: 'upload', label: '上传', permission: 'equipment:attachment', primary: true }],
    coverage: ['FR-021 至 FR-024'],
  },
  'spares.catalog': {
    key: 'spares.catalog',
    title: '备件台账',
    subTitle: '备件基础资料、适用设备、默认仓库和库存状态。',
    apiPath: '/spares/catalog',
    permission: 'spare:view',
    editPermission: 'spare:edit',
    columns: [
      { title: '备件编码', dataIndex: 'spareCode', width: 160 },
      { title: '备件名称', dataIndex: 'name', width: 170 },
      { title: '分类', dataIndex: 'category', width: 100 },
      { title: '规格', dataIndex: 'spec', width: 130 },
      { title: '单位', dataIndex: 'unit', width: 70 },
      { title: '品牌', dataIndex: 'brand', width: 100 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '默认仓库', dataIndex: 'warehouseName', width: 150 },
      { title: '库存状态', dataIndex: 'status', kind: 'status', width: 110 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'spare:edit' }, { key: 'stock', label: '库存', permission: 'spare:stock', primary: true }],
    coverage: ['FR-031', 'FR-039', 'FR-040'],
    statusSearch: true,
  },
  'spares.stock': {
    key: 'spares.stock',
    title: '库存管理',
    subTitle: '按厂区、仓库、库位管理当前库存、安全库存和预警状态。',
    apiPath: '/spares/stock',
    permission: 'spare:stock',
    editPermission: 'spare:edit',
    columns: [
      { title: '备件编码', dataIndex: 'spareCode', width: 160 },
      { title: '备件名称', dataIndex: 'name', width: 170 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '仓库', dataIndex: 'warehouseName', width: 150 },
      { title: '库位', dataIndex: 'locationCode', width: 100 },
      { title: '当前库存', dataIndex: 'stockQty', kind: 'number', width: 100 },
      { title: '安全库存', dataIndex: 'safetyStock', kind: 'number', width: 100 },
      { title: '最低库存', dataIndex: 'minStock', kind: 'number', width: 100 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction, { key: 'adjust', label: '调整', permission: 'spare:edit' }, { key: 'inventory', label: '盘点', permission: 'spare:inventory', primary: true }],
    coverage: ['FR-032', 'FR-036', 'FR-040'],
    statusSearch: true,
  },
  'spares.inbound': {
    key: 'spares.inbound',
    title: '入库管理',
    subTitle: '采购入库、退库入库、盘盈入库和来源单据追溯。',
    apiPath: '/spares/inbound',
    permission: 'spare:inbound',
    editPermission: 'spare:inbound',
    approvePermission: 'spare:approve',
    columns: [
      { title: '入库单号', dataIndex: 'billCode', width: 140 },
      { title: '入库类型', dataIndex: 'inboundType', kind: 'status', width: 110 },
      { title: '备件编码', dataIndex: 'spareCode', width: 150 },
      { title: '备件名称', dataIndex: 'spareName', width: 170 },
      { title: '数量', dataIndex: 'quantity', kind: 'number', width: 80 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '来源单据', dataIndex: 'sourceBill', width: 140 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction, { key: 'create', label: '入库', permission: 'spare:inbound', primary: true }, { key: 'approve', label: '审核', permission: 'spare:approve' }],
    coverage: ['FR-033'],
    statusSearch: true,
  },
  'spares.outbound': {
    key: 'spares.outbound',
    title: '领用出库',
    subTitle: '维修领用、保养领用、调拨出库、盘亏出库和未用退库。',
    apiPath: '/spares/outbound',
    permission: 'spare:outbound',
    editPermission: 'spare:outbound',
    approvePermission: 'spare:approve',
    columns: [
      { title: '出库单号', dataIndex: 'billCode', width: 140 },
      { title: '出库类型', dataIndex: 'outboundType', kind: 'status', width: 110 },
      { title: '备件编码', dataIndex: 'spareCode', width: 150 },
      { title: '备件名称', dataIndex: 'spareName', width: 170 },
      { title: '数量', dataIndex: 'quantity', kind: 'number', width: 80 },
      { title: '关联设备', dataIndex: 'relatedAssetCode', width: 150 },
      { title: '用途', dataIndex: 'purpose', width: 220 },
      { title: '审批状态', dataIndex: 'status', kind: 'status', width: 110 },
    ],
    actions: [viewAction, { key: 'create', label: '领用', permission: 'spare:outbound', primary: true }, { key: 'approve', label: '审批', permission: 'spare:approve' }, { key: 'return', label: '退库', permission: 'spare:outbound' }],
    coverage: ['FR-034', 'FR-035', 'FR-038'],
    statusSearch: true,
  },
  'spares.inventory': {
    key: 'spares.inventory',
    title: '备件盘点',
    subTitle: '备件盘点计划、账实差异和盘盈盘亏处理。',
    apiPath: '/spares/inventory',
    permission: 'spare:inventory',
    editPermission: 'spare:inventory',
    approvePermission: 'spare:approve',
    columns: [
      { title: '计划编号', dataIndex: 'planCode', width: 160 },
      { title: '计划名称', dataIndex: 'planName', width: 220 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '仓库', dataIndex: 'warehouseName', width: 150 },
      { title: '账面数量', dataIndex: 'expectedQty', kind: 'number', width: 100 },
      { title: '实盘数量', dataIndex: 'actualQty', kind: 'number', width: 100 },
      { title: '差异数量', dataIndex: 'diffQty', kind: 'number', width: 100 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 100 },
    ],
    actions: [viewAction, { key: 'create', label: '新建', permission: 'spare:inventory', primary: true }, { key: 'diff', label: '差异', permission: 'spare:approve' }],
    coverage: ['FR-037'],
    statusSearch: true,
  },
  'spares.alerts': {
    key: 'spares.alerts',
    title: '备件预警',
    subTitle: '低库存、超储和长期未动用备件预警及补货建议。',
    apiPath: '/spares/alerts',
    permission: 'spare:alert',
    columns: [
      { title: '预警类型', dataIndex: 'alertType', kind: 'status', width: 110 },
      { title: '备件编码', dataIndex: 'spareCode', width: 160 },
      { title: '备件名称', dataIndex: 'spareName', width: 170 },
      { title: '厂区', dataIndex: 'factoryName', width: 150 },
      { title: '仓库', dataIndex: 'warehouseName', width: 150 },
      { title: '当前库存', dataIndex: 'currentQty', kind: 'number', width: 100 },
      { title: '安全库存', dataIndex: 'safetyStock', kind: 'number', width: 100 },
      { title: '建议', dataIndex: 'suggestion', width: 260 },
    ],
    actions: [viewAction, { key: 'replenish', label: '补货', permission: 'spare:edit', primary: true }],
    coverage: ['FR-036', 'FR-052'],
    statusSearch: true,
  },
  'integrations.mom': {
    key: 'integrations.mom',
    title: 'MOM 对接',
    subTitle: '运行状态、OEE、维修保养记录和告警数据同步状态。',
    apiPath: '/integrations/mom',
    permission: 'integration:mom',
    columns: [
      { title: '系统名称', dataIndex: 'systemName', width: 180 },
      { title: '状态', dataIndex: 'state', kind: 'status', width: 100 },
      { title: '接口地址', dataIndex: 'endpoint', width: 220 },
      { title: '同步方式', dataIndex: 'syncMode', width: 110 },
      { title: '最近同步', dataIndex: 'lastSyncAt', width: 160 },
      { title: '成功率', dataIndex: 'successRate', kind: 'percent', width: 100 },
      { title: '负责人', dataIndex: 'owner', width: 130 },
    ],
    actions: [viewAction, { key: 'sync', label: '同步', permission: 'integration:mom', primary: true }],
    coverage: ['FR-041 至 FR-046', 'FR-053'],
    statusSearch: true,
  },
  'integrations.finance': {
    key: 'integrations.finance',
    title: '财务对接',
    subTitle: '固定资产编号、转固、折旧、净值和处置核销同步。',
    apiPath: '/integrations/finance',
    permission: 'integration:finance',
    columns: [
      { title: '系统名称', dataIndex: 'systemName', width: 180 },
      { title: '状态', dataIndex: 'state', kind: 'status', width: 100 },
      { title: '接口地址', dataIndex: 'endpoint', width: 220 },
      { title: '同步方式', dataIndex: 'syncMode', width: 110 },
      { title: '最近同步', dataIndex: 'lastSyncAt', width: 160 },
      { title: '成功率', dataIndex: 'successRate', kind: 'percent', width: 100 },
      { title: '负责人', dataIndex: 'owner', width: 130 },
    ],
    actions: [viewAction, { key: 'sync', label: '同步', permission: 'integration:finance', primary: true }],
    coverage: ['FR-054 至 FR-058'],
    statusSearch: true,
  },
  'integrations.project': {
    key: 'integrations.project',
    title: '项目管理对接',
    subTitle: '项目竣工验收接入和手工录入、Excel 导入替代路径。',
    apiPath: '/integrations/project',
    permission: 'integration:project',
    columns: [
      { title: '系统名称', dataIndex: 'systemName', width: 180 },
      { title: '状态', dataIndex: 'state', kind: 'status', width: 100 },
      { title: '接口地址', dataIndex: 'endpoint', width: 220 },
      { title: '同步方式', dataIndex: 'syncMode', width: 110 },
      { title: '最近同步', dataIndex: 'lastSyncAt', width: 160 },
      { title: '成功率', dataIndex: 'successRate', kind: 'percent', width: 100 },
      { title: '负责人', dataIndex: 'owner', width: 130 },
    ],
    actions: [viewAction, { key: 'import', label: '导入', permission: 'integration:project', primary: true }],
    coverage: ['FR-059', 'FR-060'],
    statusSearch: true,
  },
  'system.users': {
    key: 'system.users',
    title: '用户管理',
    subTitle: '用户、角色、所属组织、状态和数据范围配置。',
    apiPath: '/system/users',
    permission: 'system:user',
    editPermission: 'system:user',
    columns: [
      { title: '姓名', dataIndex: 'name', width: 100 },
      { title: '账号', dataIndex: 'username', width: 120 },
      { title: '角色', dataIndex: 'roleName', width: 150 },
      { title: '所属组织', dataIndex: 'factoryName', width: 160 },
      { title: '部门', dataIndex: 'department', width: 140 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 90 },
    ],
    actions: [viewAction, { key: 'edit', label: '编辑', permission: 'system:user', primary: true }],
    coverage: ['角色权限管理', '数据范围配置'],
    statusSearch: true,
  },
  'system.roles': {
    key: 'system.roles',
    title: '角色权限',
    subTitle: '角色定义、菜单权限、按钮权限和数据权限配置。',
    apiPath: '/system/roles',
    permission: 'system:role',
    editPermission: 'system:role',
    columns: [
      { title: '角色名称', dataIndex: 'roleName', width: 160 },
      { title: '菜单权限数', dataIndex: 'menuCount', kind: 'number', width: 110 },
      { title: '按钮权限数', dataIndex: 'buttonCount', kind: 'number', width: 110 },
      { title: '数据范围', dataIndex: 'dataScope', width: 120 },
      { title: '说明', dataIndex: 'description', width: 300 },
      { title: '状态', dataIndex: 'status', kind: 'status', width: 90 },
    ],
    actions: [viewAction, { key: 'edit', label: '配置', permission: 'system:role', primary: true }],
    coverage: ['菜单权限', '按钮权限', '数据权限'],
    statusSearch: true,
  },
  'system.logs': {
    key: 'system.logs',
    title: '操作日志',
    subTitle: '操作人、模块、动作、结果、时间和业务对象追溯。',
    apiPath: '/system/logs',
    permission: 'system:log',
    columns: [
      { title: '操作人', dataIndex: 'operator', width: 100 },
      { title: '模块', dataIndex: 'module', width: 130 },
      { title: '动作', dataIndex: 'action', width: 150 },
      { title: '对象', dataIndex: 'target', width: 160 },
      { title: '结果', dataIndex: 'result', kind: 'status', width: 90 },
      { title: 'IP', dataIndex: 'ip', width: 120 },
      { title: '时间', dataIndex: 'createdAt', width: 160 },
    ],
    actions: [viewAction],
    coverage: ['FR-017', '操作日志'],
    statusSearch: true,
  },
};

export const managementPageConfigs: Record<string, ManagementPageConfig> = {
  ...basePageConfigs,
  ...extensionPageConfigs,
};
